### PR TITLE
Changed doxygen tool for generating taf docs to sphinx

### PR DESCRIPTION
**Pull request by IrynaBarna**
Signed-off-by: Iryna Barna <irynax.barna@intel.com>

@rbbratta, @seungweonpark, @NazarTkachuk, @esmacgil, @lijenni please review.

---
This change is [Reviewable](https://reviewable.io/reviews/taf3/taf/25)

### CODE REVIEW

**Comment by esmacgil** [comment]
Reviewed 46 of 46 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[requirements.txt, line 21 at r1](https://reviewable.io:443/reviews/taf3/taf/25#-KdXN4teNY9kUADgP9eF:-KdXN4teNY9kUADgP9eG:b1e7roq) ([raw file](https://github.com/taf3/taf/blob/7ef2c614599e2fa4871a7450bf4543c5e1a6ba11/requirements.txt#L21)):*
> ```
> sphinx_rtd_theme
> sphinxcontrib-napoleon
> autoapi
> ```

It may not matter, but I'd think we should have a newline here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25)*

**Comment by NazarTkachuk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/pages/6_4_taf_coding_config_structure.dox, line 96 at r1](https://reviewable.io:443/reviews/taf3/taf/25#-Kde8ZfQu0I0rO1_etLm:-Kde8ZfQu0I0rO1_etLn:b-ibqxba) ([raw file](https://github.com/taf3/taf/blob/a3983f952bb91db43015548667a28f921b99805e/docs/pages/6_4_taf_coding_config_structure.dox#L96)):*
> ```
> \b Vlab:
> \code{.json}
> {"entry_type": "cross", "instance_type": "vlab", "id": "2", "ip_host": "localhost", "ip_port": "8050", "ifaces": ["vlab0", "vlab1", "vlab2", "vlab3", "vlab4"], "tgmap": [0], "related_id": [1]}
> ```

Please use "ports" instead of "ifaces" because option is outdated and is not used. 
Replace in all the other similar places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25)*

**Comment by NazarTkachuk** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/source/test_execution_preconfiguration.rst, line 35 at r1](https://reviewable.io:443/reviews/taf3/taf/25#-KdeJ0JlmM7ZqQ9GI5AA:-KdeJ0JlmM7ZqQ9GI5AB:bwmvhy2) ([raw file](https://github.com/taf3/taf/blob/7ef2c614599e2fa4871a7450bf4543c5e1a6ba11/docs/source/test_execution_preconfiguration.rst#L35)):*
> ```reStructuredText
>    {
>    "env": [
>            {"id": 0, "ifaces": [[1, 1, 6], [1, 1, 7], [1, 1, 8], [1, 1, 9], [1, 1, 10], [1, 1, 11], [1, 1, 12], [1, 1, 13], [1, 1, 14]]},
> ```

Please use "ports" instead of "ifaces" because option is outdated and is not used.
Replace in all the other similar places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25)*

**Comment by IrynaBarna** [comment]
Review status: 38 of 47 files reviewed at latest revision, 3 unresolved discussions.

---

*[requirements.txt, line 21 at r1](https://reviewable.io:443/reviews/taf3/taf/25#-KdXN4teNY9kUADgP9eF:-KeDNrlrBG-il7TSAPvE:b-896fix) ([raw file](https://github.com/taf3/taf/blob/7ef2c614599e2fa4871a7450bf4543c5e1a6ba11/requirements.txt#L21)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

It may not matter, but I'd think we should have a newline here.
</blockquote></details>

Done.

---

*[docs/pages/6_4_taf_coding_config_structure.dox, line 96 at r1](https://reviewable.io:443/reviews/taf3/taf/25#-Kde8ZfQu0I0rO1_etLm:-KeDNtnU5IbpKzDldHAz:b-896fix) ([raw file](https://github.com/taf3/taf/blob/a3983f952bb91db43015548667a28f921b99805e/docs/pages/6_4_taf_coding_config_structure.dox#L96)):*
<details><summary><i>Previously, NazarTkachuk (Nazar Tkachuk) wrote…</i></summary><blockquote>

Please use "ports" instead of "ifaces" because option is outdated and is not used. 
Replace in all the other similar places.
</blockquote></details>

Done.

---

*[docs/source/test_execution_preconfiguration.rst, line 35 at r1](https://reviewable.io:443/reviews/taf3/taf/25#-KdeJ0JlmM7ZqQ9GI5AA:-KeDNuxyC8vdzvCUXOOH:b-896fix) ([raw file](https://github.com/taf3/taf/blob/7ef2c614599e2fa4871a7450bf4543c5e1a6ba11/docs/source/test_execution_preconfiguration.rst#L35)):*
<details><summary><i>Previously, NazarTkachuk (Nazar Tkachuk) wrote…</i></summary><blockquote>

Please use "ports" instead of "ifaces" because option is outdated and is not used.
Replace in all the other similar places.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25)*

**Comment by esmacgil** [comment]
Reviewed 1 of 46 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25)*

**Comment by esmacgil** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[taf/plugins/loggers.py, line 1 at r2](https://reviewable.io:443/reviews/taf3/taf/25#-KeFrLNDbdtWxsNa8VtX:-KeFrLNDbdtWxsNa8VtY:btwt1kz) ([raw file](https://github.com/taf3/taf/blob/68adc1d23ab9722319ba0d19019678d01210f966/taf/plugins/loggers.py#L1)):*
> ```Python
> # Copyright (c) 2011 - 2016, Intel Corporation.
> ```

Update copyright ending year.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25)*

**Comment by esmacgil** [comment]
I didn't read all the doc changes and you probably would want the code changes in another request, but there seems to be a few parts of the code to make better.

---

Reviewed 28 of 28 files at r3.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[reporting/reporting_server.py, line 67 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLQCszxnLiQMYVdN57:-KeLQCszxnLiQMYVdN58:bze1v62) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L67)):*
> ```Python
> 
>         """
>         self._lock = RLock()
> ```

Why don't we use this as a context?

```
with self._lock:
    # take sensitive actions
# do non-sensitive action
```

---

*[reporting/reporting_server.py, line 87 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLQeNe-l_t4sVT9VGr:-KeLQeNe-l_t4sVT9VGs:b-h89nup) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L87)):*
> ```Python
>         _ok = False
>         self._lock.acquire()
>         try:
> ```

And here I would make it possible to combine with suppress, but the native version wouldn't enable what I want:

```
with self.class_logger.suppress(message='...', exc_tuple=Exception), self._lock:
    self.queue.append(cmd)
    self.class_logger.info('Command added successfully. CMD keys: %s', list(cmd.keys()))
    return True
return False
```

---

*[reporting/reporting_server.py, line 109 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLSOnZf4gBJxCYCRcb:-KeLSOnZf4gBJxCYCRcc:b-z2eecg) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L109)):*
> ```Python
>         self._lock.acquire()
>         try:
>             if len(self.queue) > 0:
> ```

Do we really have to calculate the length?

```
try:
    return self.queue.pop(0)
except IndexError:
    return None
```

Must we really force the first value to be popped?  Sure, that can be the default, but must it be the only thing allowed?

---

*[reporting/reporting_server.py, line 869 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLTWBUWh7MfqxMwAcO:-KeLTWBUWh7MfqxMwAcP:b-y8v8v3) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L869)):*
> ```Python
> 
>         """
>         self.class_logger.debug("Kwargs: %s" % (str(kwargs), ))
> ```

Logging after building a string, please:

```
self.class_logger.debug('Kwargs: %s', kwargs)
```

---

*[reporting/reporting_server.py, line 870 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLTelzyCgvGQxHhsrh:-KeLTelzyCgvGQxHhsri:b-xw2cnc) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L870)):*
> ```Python
>         """
>         self.class_logger.debug("Kwargs: %s" % (str(kwargs), ))
>         try:
> ```

Use `suppress` please and do we really expect the `if` or assignment to `cmd` to raise an  exception?

```
if info is None:
    info = {}

cmd = {...}

with suppress(Exception):
    self.queue.add(cmd)
    return True
return False
```

---

*[reporting/reporting_server.py, line 951 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLVkWLq21wfBEcHUe0:-KeLVkWLq21wfBEcHUe1:b-wy4xin) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L951)):*
> ```Python
>             return True
>         else:
>             self.class_logger.info("Queue processing start canceled. Reason - it is disabled.")
> ```

Simple paths should come first, especially if they return from the function early:

```
if not self.watchdog:
    self.class_logger.info(...)
    return False

if self.watchdog_thr is None:
    # first start
    self.class_logger.info(...)
    start_thr()
elif self.watchdog_thr.is_alive():
    self.class_logger.info(...)
else:
    # thread is dead
    ...
return True
```

---

*[reporting/reporting_server.py, line 965 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLVGZblif0sKdKpK8F:-KeLVGZblif0sKdKpK8G:b4tcifu) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L965)):*
> ```Python
>         """
>         # Truncating command for log message
>         cmd1 = cmd.copy()
> ```

Why not:

```
cmd1 = {k: v for k, v in cmd.items() if k not in ['report']}
self.class_logger.info('...: %s', cmd1)
```

---

*[reporting/reporting_server.py, line 1017 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLUoJbpMqJo6GplRHz:-KeLUoJbpMqJo6GplRI-:b-goo78) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L1017)):*
> ```Python
>         cinprocess = self.clients.inprocess()
>         self.class_logger.info("Clients in process: {0}".format(cinprocess))
>         if qlen == 0 and len(cinprocess) == 0:
> ```

Don't test and return Boolean literals.

```
return qlen == 0 and cinprocess
```

---

*[reporting/reporting_server.py, line 1078 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLTo-qB6KDsi0kPORL:-KeLTo-qB6KDsi0kPORM:b1ixfzv) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L1078)):*
> ```Python
> 
>     """
>     sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
> ```

Please use `contextlib.closing` and don't manage the garbage collector (`del sock`):

```
with contextlib.closing(socket.socket(socket.AF._INET, socket.SOCK_STREAM) as sock:
    sock.bind(('', 0))
    return sock.getsockname()[1]
```

---

*[reporting/reporting_server.py, line 1122 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLUJ4SEhLqLm_WYmJZ:-KeLUJ4TvHahxy2lNGUm:bqxdqtk) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L1122)):*
> ```Python
>     _vr = None
>     try:
>         _vr = open(_vr_path, "w")
> ```

`open` is a context manager:

```
try:
    with open(_vr_path, 'w') as _vr:
        _vr.write(str(port))
except Exception as err:
    ...
...
```

---

*[reporting/reports/XML.py, line 555 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLYUMcaGFSZGePW45f:-KeLYUMdLiwszF2WhPs3:bl6x3xi) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reports/XML.py#L555)):*
> ```Python
>         """
>         self.class_logger.info("Appending XML report with fail.")
>         for i in range(len(report['sections'])):
> ```

Why not:

```
report['sections'] = [xml_unescape(section) for section in report['sections']]
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25#-:-KeLZkb_J_5ryUNaecOa:b-xg30c0)*

**Comment by esmacgil** [comment]
Reviewed 70 of 70 files at r4.
Review status: 144 of 145 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25)*

**Comment by esmacgil** [comment]
Reviewed 1 of 46 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25)*

**Comment by IrynaBarna** [comment]
I'll update code according to your comments when I finish activities with docstrings. Also I'll fix `pylint` blocking errors.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25#-:-KfC4N0BLokN2iamhpv-:by65nzu)*

**Comment by esmacgil** [comment]
Reviewed 30 of 80 files at r5.
Review status: 170 of 220 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25)*

**Comment by esmacgil** [comment]
Reviewed 12 of 80 files at r5, 19 of 23 files at r6.
Review status: 183 of 223 files reviewed at latest revision, 20 unresolved discussions.

---

*[reporting/reports/XML.py, line 623 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfT1w4ycswYKlF8jY-1:-KfT1w4zlhV-tAbPDJE0:b-wodks7) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/reporting/reports/XML.py#L623)):*
> ```Python
> 
>         _path_arr = dump_logfile.split("/")
>         if _path_arr and not os.path.exists(dump_logfile[:-len(_path_arr[-1])]):
> ```

I'm unaware of how `_path_arr` could not be `True` here, splitting the empty string results in a list with the empty string as its only member, which is a `True` list (`bool(['']` is `True`).  Then, if all we want here is the `dirname` of `dump_logfile`, then why not use `os.path.dirname`?

---

*[reporting/reports/XML.py, line 638 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfT0U3mPJgDdB9sx43K:-KfT0U3oxnJ86Cwewkys:b-8wrn7p) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/reporting/reports/XML.py#L638)):*
> ```Python
>         if self.infodict:
>             info_nodes = []
>             for info_node in list(self.infodict.keys()):
> ```

Why do we need the list of `keys`?  I don't see any updating of `self.infodict` within the loop.  To me this should be:

```
if self.infodict:
    self.tests.append(self.Junit.header([self.Junit.info_node(value, key) for key, value in self.infodcit.items()]))
try:
    ...
```

Though it seems likely to have to go multi-line to get the `pylint: disable` comments.

---

*[reporting/reports/XML.py, line 658 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfT3Jy1uBSIuzf1xv6z:-KfT3Jy2W8gFgnfVfoUu:b-kwo3i4) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/reporting/reports/XML.py#L658)):*
> ```Python
>         except Exception as err:
>             self.class_logger.error("Cannot dump XML report to file {0}. ERRTYPE: {1}, ERR: {2}".format(dump_logfile, type(err), err))
>             logfile.close()
> ```

This seems to be needed in both paths, so it seems better as a statement in a `finally` clause.  Or better yet, handled by a context manager.

---

*[taf/testlib/helpers.py, line 534 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfTJND09Iptpi9Sxq9p:-KfTJND1YJpXxXJA-Yfa:bto3bfv) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/taf/testlib/helpers.py#L534)):*
> ```Python
>         if row['field'] == field and row['mask'] == mask and row['data'] == data:
>             row_count += 1
>     if row_count == 1:
> ```

Returning literals immediately after a test:

```
return row_count == 1
```

Of course, as soon as `row_count` hits `2` inside the `for` loop, we could return `False` and `row_count` could really become the result tracker:

```
table = ...
one_match = False
for row in table:
    if row['field'] == field and row['mask'] == mask and row['data'] == data:
        if one_match:
            return False
        one_match = True
return one_match
```

---

*[taf/testlib/helpers.py, line 560 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfTKtG_CyylyFSwMQw7:-KfTKtG_CyylyFSwMQw8:b-8vf0vi) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/taf/testlib/helpers.py#L560)):*
> ```Python
>         if row['action'] == action and row['param'] == param:
>             row_count += 1
>     if row_count == 1:
> ```

See comment to line 534.

---

*[taf/testlib/helpers.py, line 594 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfTL1nxkM--pN4uixmg:-KfTL1nxkM--pN4uixmh:b-8vf0vi) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/taf/testlib/helpers.py#L594)):*
> ```Python
>            row['enabled'] == enabled and row['priority'] == priority:
>             row_count += 1
>     if row_count == 1:
> ```

See comment to line 534.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25)*

**Comment by IrynaBarna** [comment]
Review status: 130 of 276 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[reporting/reporting_server.py, line 67 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLQCszxnLiQMYVdN57:-KfgXUZp25u3CS7ishxh:bvwt6ys) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L67)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Why don't we use this as a context?

```
with self._lock:
    # take sensitive actions
# do non-sensitive action
```
</blockquote></details>

Updated all similar places.

---

*[reporting/reporting_server.py, line 87 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLQeNe-l_t4sVT9VGr:-KgOFZ7Gxaw6XfC6OxKM:b-qjnvx2) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L87)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

And here I would make it possible to combine with suppress, but the native version wouldn't enable what I want:

```
with self.class_logger.suppress(message='...', exc_tuple=Exception), self._lock:
    self.queue.append(cmd)
    self.class_logger.info('Command added successfully. CMD keys: %s', list(cmd.keys()))
    return True
return False
```
</blockquote></details>

Please take a look on my approach. I used decorator to log error message. 

---

*[reporting/reporting_server.py, line 109 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLSOnZf4gBJxCYCRcb:-KfgYK56WgBj3iYkvfEj:b-f128ev) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L109)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Do we really have to calculate the length?

```
try:
    return self.queue.pop(0)
except IndexError:
    return None
```

Must we really force the first value to be popped?  Sure, that can be the default, but must it be the only thing allowed?
</blockquote></details>

The first value is needed to force in accordance to processing of reports queue. 

---

*[reporting/reporting_server.py, line 869 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLTWBUWh7MfqxMwAcO:-KfgYO5LCTUZNGBiMq0O:b-56frok) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L869)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Logging after building a string, please:

```
self.class_logger.debug('Kwargs: %s', kwargs)
```
</blockquote></details>

Updated all similar places. 

---

*[reporting/reporting_server.py, line 870 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLTelzyCgvGQxHhsrh:-KfjysKMZDK-ALN6c9OB:b-896fix) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L870)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Use `suppress` please and do we really expect the `if` or assignment to `cmd` to raise an  exception?

```
if info is None:
    info = {}

cmd = {...}

with suppress(Exception):
    self.queue.add(cmd)
    return True
return False
```
</blockquote></details>

Done.

---

*[reporting/reporting_server.py, line 951 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLVkWLq21wfBEcHUe0:-KfgYy5IR1d9DURWq92f:b-896fix) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L951)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Simple paths should come first, especially if they return from the function early:

```
if not self.watchdog:
    self.class_logger.info(...)
    return False

if self.watchdog_thr is None:
    # first start
    self.class_logger.info(...)
    start_thr()
elif self.watchdog_thr.is_alive():
    self.class_logger.info(...)
else:
    # thread is dead
    ...
return True
```
</blockquote></details>

Done.

---

*[reporting/reporting_server.py, line 965 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLVGZblif0sKdKpK8F:-KfgZD_XGqIgCcbo6TBK:b-896fix) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L965)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Why not:

```
cmd1 = {k: v for k, v in cmd.items() if k not in ['report']}
self.class_logger.info('...: %s', cmd1)
```
</blockquote></details>

Done.

---

*[reporting/reporting_server.py, line 1017 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLUoJbpMqJo6GplRHz:-Kfjz7WtufiRw_TkMFPE:b-896fix) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L1017)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Don't test and return Boolean literals.

```
return qlen == 0 and cinprocess
```
</blockquote></details>

Done.

---

*[reporting/reporting_server.py, line 1078 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLTo-qB6KDsi0kPORL:-Kfk5vNmHWmuEipHWlnC:b-896fix) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L1078)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Please use `contextlib.closing` and don't manage the garbage collector (`del sock`):

```
with contextlib.closing(socket.socket(socket.AF._INET, socket.SOCK_STREAM) as sock:
    sock.bind(('', 0))
    return sock.getsockname()[1]
```
</blockquote></details>

Done.

---

*[reporting/reporting_server.py, line 1122 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLUJ4SEhLqLm_WYmJZ:-KfkBfdfNqV0AquRoSDb:b-896fix) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reporting_server.py#L1122)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

`open` is a context manager:

```
try:
    with open(_vr_path, 'w') as _vr:
        _vr.write(str(port))
except Exception as err:
    ...
...
```
</blockquote></details>

Done.

---

*[reporting/reports/XML.py, line 555 at r3](https://reviewable.io:443/reviews/taf3/taf/25#-KeLYUMcaGFSZGePW45f:-KfkKkj2zLOnRXyHFxQo:b-896fix) ([raw file](https://github.com/taf3/taf/blob/8582c6677408f6c4a6ff389f0dfc98b9eeedb330/reporting/reports/XML.py#L555)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Why not:

```
report['sections'] = [xml_unescape(section) for section in report['sections']]
```
</blockquote></details>

Done.

---

*[reporting/reports/XML.py, line 623 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfT1w4ycswYKlF8jY-1:-KfkWi2S_34bFsSa7YIA:b-896fix) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/reporting/reports/XML.py#L623)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

I'm unaware of how `_path_arr` could not be `True` here, splitting the empty string results in a list with the empty string as its only member, which is a `True` list (`bool(['']` is `True`).  Then, if all we want here is the `dirname` of `dump_logfile`, then why not use `os.path.dirname`?
</blockquote></details>

Done.

---

*[reporting/reports/XML.py, line 638 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfT0U3mPJgDdB9sx43K:-Kfkd3UjMadCBz6uejL8:b-896fix) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/reporting/reports/XML.py#L638)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Why do we need the list of `keys`?  I don't see any updating of `self.infodict` within the loop.  To me this should be:

```
if self.infodict:
    self.tests.append(self.Junit.header([self.Junit.info_node(value, key) for key, value in self.infodcit.items()]))
try:
    ...
```

Though it seems likely to have to go multi-line to get the `pylint: disable` comments.
</blockquote></details>

Done.

---

*[reporting/reports/XML.py, line 658 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfT3Jy1uBSIuzf1xv6z:-Kfpl-Z5pgUTpUnGojMK:b-896fix) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/reporting/reports/XML.py#L658)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

This seems to be needed in both paths, so it seems better as a statement in a `finally` clause.  Or better yet, handled by a context manager.
</blockquote></details>

Done.

---

*[taf/plugins/loggers.py, line 1 at r2](https://reviewable.io:443/reviews/taf3/taf/25#-KeFrLNDbdtWxsNa8VtX:-KfkesZJhPnEoEC1cn4L:b-896fix) ([raw file](https://github.com/taf3/taf/blob/68adc1d23ab9722319ba0d19019678d01210f966/taf/plugins/loggers.py#L1)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Update copyright ending year.
</blockquote></details>

Done.

---

*[taf/testlib/helpers.py, line 534 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfTJND09Iptpi9Sxq9p:-KfkqfBkPUpsAW6NOzvc:b-896fix) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/taf/testlib/helpers.py#L534)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Returning literals immediately after a test:

```
return row_count == 1
```

Of course, as soon as `row_count` hits `2` inside the `for` loop, we could return `False` and `row_count` could really become the result tracker:

```
table = ...
one_match = False
for row in table:
    if row['field'] == field and row['mask'] == mask and row['data'] == data:
        if one_match:
            return False
        one_match = True
return one_match
```
</blockquote></details>

Done.

---

*[taf/testlib/helpers.py, line 560 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfTKtG_CyylyFSwMQw7:-KfkqermWWQ1zEXg1CCA:b-896fix) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/taf/testlib/helpers.py#L560)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

See comment to line 534.
</blockquote></details>

Done.

---

*[taf/testlib/helpers.py, line 594 at r6](https://reviewable.io:443/reviews/taf3/taf/25#-KfTL1nxkM--pN4uixmg:-KfkqeS-2XcFbXDa5vMh:b-896fix) ([raw file](https://github.com/taf3/taf/blob/31d887be41dd094ac72676b9b2635ebf679a042f/taf/testlib/helpers.py#L594)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

See comment to line 534.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/25)*

**Pull request merged**
