### PR TITLE
Added support of LLDP and LACP protocols

### PR DESCRIPTION
**Pull request by NazarTkachuk**
Signed-off-by: Tkachuk <nazarx.tkachuk@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/taf3/taf/38)

### CODE REVIEW

**Comment by NazarTkachuk** [comment]
Please review @rbbratta @seungweonpark @lijenni @esmacgil

**Comment by esmacgil** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[taf/testlib/packet_processor.py, line 274 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYWbmkbO52559ZFqLA:-KhYWbmkbO52559ZFqLB:b-h23dnr) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L274)):*
> ```Python
>             with suppress(KeyError):
>                 tlvlist_def = layer["LLDP"]["tlvlist"]
>                 first = operator.itemgetter(0)
> ```

This seems to be needed in multiple places and it is within a `for` loop, I'd prefer defining it before the `for` loop.

---

*[taf/testlib/packet_processor.py, line 275 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYVxDAGnEHROQTOvqG:-KhYVxDBA9Ob73fZ3lz-:bhqi22) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L275)):*
> ```Python
>                 tlvlist_def = layer["LLDP"]["tlvlist"]
>                 first = operator.itemgetter(0)
>                 tlvlist = []
> ```

Why not assign the list to `packet.lldp.tlvlist` here and avoid having to do the assignment after the `for` loop?

```
packet.lldp.tlvlist = tlvlist = []
```

So the new list gets assigned to the long-term name (`packet.lldp.tlvlist`) and a local name (`tlvlist`) at the same time.

---

*[taf/testlib/packet_processor.py, line 293 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYWPEy5wsqxb6d1SBP:-KhYWPEy5wsqxb6d1SBQ:bjpsb34) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L293)):*
> ```Python
>                 tlvlist_def = layer["LACP"]["tlvlist"]
>                 first = operator.itemgetter(0)
>                 tlvlist = []
> ```

See comment for line 275.

---

*[taf/testlib/packet_processor.py, line 414 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYY-JXiLwVmcSyw3xx:-KhYY-JXiLwVmcSyw3xy:buio20c) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L414)):*
> ```Python
>             elif layer.startswith("LACP"):
>                 pypacker_layer = self._get_pypacker_layer("LACP")
>             for tlv in getattr(packet[pypacker_layer], "tlvlist", [])[:]:
> ```

Why do we need to make a shallow copy of the list?

---

*[taf/testlib/packet_processor.py, line 478 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYYYWgbaCp8OFyONTH:-KhYYYWgbaCp8OFyONTI:bpi1k14) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L478)):*
> ```Python
>                     layer_dict[class_name][field] = opts
>                 elif field == "tlvlist" and class_name in ["LLDP", "LACP"]:
>                     for tlv in self.get_packet_field(packet, class_name, field)[:]:
> ```

It seems shallow copies are commonplace.

---

*[unittests/traffic_generator/test_tg.py, line 75 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYZeC18xM-LGWdpnf1:-KhYZeC2NZ4Vo8YXffAp:b-8em5r2) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L75)):*
> ```Python
>                     "Field '{packet.field}' with value {packet.value} from " \
>                     "layer '{packet.layer}' is not found in received packet".format(packet=init_param)
>             else:
> ```

Can we use a `continue` statement in the truth clause instead of this `else` and its clause?

---

*[unittests/traffic_generator/test_tg.py, line 1140 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYb16X4BAl6vy3Htet:-KhYb16X4BAl6vy3Hteu:bc9zfik) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L1140)):*
> ```Python
>         # Verify that LLDP Chassis macs are different
>         mac_set = set([tg.get_packet_field(packet, "Ethernet", "src") for packet in packets])
>         lldp_set = set([tg.get_packet_field(packet, "LLDPChassisId", "value") for packet in packets])
> ```

The `set` constructor will take an iterable, no need for the `list` between the iteration and constructor here.

```
lldp_set = set(tg.get_packet_field(...) for packet in packets)
```

---

*[unittests/traffic_generator/test_tg.py, line 1162 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYbLVepC-XApVIWWxs:-KhYbLVepC-XApVIWWxt:b90a0ig) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L1162)):*
> ```Python
>         # Verify that LLDP Chassis macs are different
>         mac_set = set([tg.get_packet_field(packet, "Ethernet", "src") for packet in packets])
>         lldp_set = set([tg.get_packet_field(packet, "LLDPChassisId", "value") for packet in packets])
> ```

See comment to line 1140.

---

*[unittests/traffic_generator/test_tg.py, line 1185 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYbQnBv9EmWY3BlTZi:-KhYbQnBv9EmWY3BlTZj:bpals7s) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L1185)):*
> ```Python
> 
>         # Verify that LLDP Chassis macs are different
>         mac_set = set([tg.get_packet_field(packet, "Ethernet", "src") for packet in packets])
> ```

See comment to line 1140 for this line and the next.

---

*[unittests/traffic_generator/test_tg.py, line 1209 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYb_ZVSwL47dE6fgRt:-KhYb_ZVSwL47dE6fgRu:b-fnd1vn) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L1209)):*
> ```Python
> 
>         # Verify that LLDP Chassis macs are different
>         mac_set = set([tg.get_packet_field(packet, "Ethernet", "src") for packet in packets])
> ```

Line 1140 again, twice.

---

*[unittests/traffic_generator/test_tg.py, line 3614 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYhmtg-rZuvUmEebM8:-KhYhmtg-rZuvUmEebM9:b-hj8pmq) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L3614)):*
> ```Python
>         lldp_pack[1]["LLDP"]["tlvlist"].insert(-1, lldp_managment_with_oid)
>         lldp_pack[1]["LLDP"]["tlvlist"].insert(-1, lldp_org_spec_tlv_1)
>         lldp_pack[1]["LLDP"]["tlvlist"].insert(-1, lldp_org_spec_tlv_2)
> ```

Perhaps make these three lines:

```
lldp_pack[1]['LLDP'['tlvlist'][-1:-1] = [lldp_management_with_oid, lldp_org_spec_tlv_1, lldp_org_spec_tlv_2]
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/38)*

**Comment by NazarTkachuk** [comment]
Review status: 2 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[taf/testlib/packet_processor.py, line 274 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYWbmkbO52559ZFqLA:-KhbynebVPYjVoZlulBb:b-896fix) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L274)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

This seems to be needed in multiple places and it is within a `for` loop, I'd prefer defining it before the `for` loop.
</blockquote></details>

Done.

---

*[taf/testlib/packet_processor.py, line 275 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYVxDAGnEHROQTOvqG:-KhboRZ-a3fB3j3nzTwH:bzf2edc) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L275)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Why not assign the list to `packet.lldp.tlvlist` here and avoid having to do the assignment after the `for` loop?

```
packet.lldp.tlvlist = tlvlist = []
```

So the new list gets assigned to the long-term name (`packet.lldp.tlvlist`) and a local name (`tlvlist`) at the same time.
</blockquote></details>

It doesn't work

    292                     first = operator.itemgetter(0)
    293                     packet.lacp.tlvlist = tlvlist = []
    294                     for tlv_dict in tlvlist_def:
    295                         tlv_type = next(iter(tlv_dict))
    296                         tlvlist.append(_pypacker_layer({tlv_type: OrderedDict(sorted(tlv_dict[tlv_type].items(), key=first))}))
    297  ->                 import pdb;pdb.set_trace()
    298
    299             # Adjust packet size with padding.
    300             if adjust_size:
    301                 packet_length = len(packet)
    302                 if packet_length < required_size:
    (Pdb) packet.lacp.tlvlist
    []
    (Pdb) tlvlist
    [LACPActorInfoTlv(type=1, len=14, sysprio=8000, sys=b'\x00\x00 \x00\x10\x02', key=0, portprio=8000, port=2, state=AB,      reserved=b'\x00\x00\x00', bytes=b''), LACPPartnerInfoTlv(type=2, len=14, sysprio=8000, sys=b'\x00\x00 \x00\x10\x02', key=0, portprio=8000, port=1, state=AD, reserved=b'\x00\x00\x00', bytes=b''), LACPCollectorInfoTlv(type=3, len=10, maxdelay=A, reserved=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', bytes=b''), LACPTerminatorTlv(type=0, len=0, bytes=b''), LACPReserved(reserved=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', bytes=b'')]

---

*[taf/testlib/packet_processor.py, line 293 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYWPEy5wsqxb6d1SBP:-KhbqKN4v_86NJhI79Bg:b6z3hov) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L293)):*
> See comment for line 275.

I removed `tlvlist`

---

*[taf/testlib/packet_processor.py, line 414 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYY-JXiLwVmcSyw3xx:-Khbrh6Jh8EJ1f3DS_4c:b-b9cfa9) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L414)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Why do we need to make a shallow copy of the list?
</blockquote></details>

I didn't investigate, but it doesn't work without copying. See logs below

    > /root/taf/taf/testlib/packet_processor.py(415)search_pypacker_layer_in_packet()

    -> for tlv in getattr(packet[pypacker_layer], "tlvlist", [])[:]:
    (Pdb) for tlv in getattr(packet[pypacker_layer], "tlvlist", []): tlv
    (Pdb) for tlv in getattr(packet[pypacker_layer], "tlvlist", [])[:]: tlv
    LLDPChassisId(type_len=207, subtype=4, value=b'\x00\x00 \x00\x10\x02', bytes=b'')
    LLDPPortId(type_len=404, subtype=1, value=b'ge0', bytes=b'')
    LLDPTTL(type_len=602, seconds=28, bytes=b'')
    LLDPPortDescription(type_len=800, value=b'', bytes=b'')
    LLDPSystemName(type_len=A0A, value=b'<sys-name>', bytes=b'')
    LLDPSystemDescription(type_len=C0A, value=b'<sys-desc>', bytes=b'')
    LLDPSystemCapabilities(type_len=E04, capabilities=4, enabled=4, bytes=b'')
    LLDPManagementAddress(type_len=100C, addrlen=5, addrsubtype=1, addrval=b'\x14\x00\n\x02', ifsubtype=2, ifnumber=3E9, oidlen=0,   oid=b'', bytes=b'')
    LLDPDUEnd(tlv_type=0, tlv_len=0, bytes=b'')

---

*[taf/testlib/packet_processor.py, line 478 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYYYWgbaCp8OFyONTH:-KhbsIcaHlWKM2_sM3NX:b-3y2smj) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L478)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

It seems shallow copies are commonplace.
</blockquote></details>

See comment for line 414

---

*[unittests/traffic_generator/test_tg.py, line 75 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYZeC18xM-LGWdpnf1:-Khc-_BrptiIYMoTWfZa:b-lzvexi) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L75)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Can we use a `continue` statement in the truth clause instead of this `else` and its clause?
</blockquote></details>

I don't get

---

*[unittests/traffic_generator/test_tg.py, line 1140 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYb16X4BAl6vy3Htet:-KhbxJKQkF_jndU0KAr8:b-896fix) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L1140)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

The `set` constructor will take an iterable, no need for the `list` between the iteration and constructor here.

```
lldp_set = set(tg.get_packet_field(...) for packet in packets)
```
</blockquote></details>

Done.

---

*[unittests/traffic_generator/test_tg.py, line 1162 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYbLVepC-XApVIWWxs:-KhbxKRSCq-j26pXJf28:b-896fix) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L1162)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

See comment to line 1140.
</blockquote></details>

Done.

---

*[unittests/traffic_generator/test_tg.py, line 1185 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYbQnBv9EmWY3BlTZi:-KhbxL7x6bIwYpYDYAi2:b-896fix) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L1185)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

See comment to line 1140 for this line and the next.
</blockquote></details>

Done.

---

*[unittests/traffic_generator/test_tg.py, line 1209 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYb_ZVSwL47dE6fgRt:-KhbxMd4Hflht5ripOHP:b-896fix) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L1209)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Line 1140 again, twice.
</blockquote></details>

Done.

---

*[unittests/traffic_generator/test_tg.py, line 3614 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYhmtg-rZuvUmEebM8:-Khby4hZ5_qMPIZjn3xP:b-896fix) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L3614)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Perhaps make these three lines:

```
lldp_pack[1]['LLDP'['tlvlist'][-1:-1] = [lldp_management_with_oid, lldp_org_spec_tlv_1, lldp_org_spec_tlv_2]
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/38)*

**Comment by esmacgil** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[taf/testlib/packet_processor.py, line 275 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYVxDAGnEHROQTOvqG:-Khd1ZZK_SGGX1qmC5RG:b-z1yan1) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L275)):*
Strange, every way that I test it, it works as I expect.

```
>>> class MyO(object):
...   pass
...
>>> myo1 = MyO()
>>> myo1.x = MyO()
>>> myo1.x.y = y = []
>>> myo1.x.y is y
True
>>> y.append(MyO())
>>> y
[<__main__.MyO object at 0x0000000002D871D0>]
>>> myo1.x.y
[<__main__.MyO object at 0x0000000002D871D0>]
```

I don't see an assignment to `packet.lldp` since creating `packet`, what type is `packet.lldp`?  Is this the same type that `packet.lacp` is?

Would `packet.lldp` have a `__setattr__` that does a copy of data before assigning it?

---

*[taf/testlib/packet_processor.py, line 414 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYY-JXiLwVmcSyw3xx:-Khd4xGAZvQTcmXrUxeL:brsaski) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L414)):*
<details><summary><i>Previously, NazarTkachuk (Nazar Tkachuk) wrote…</i></summary><blockquote>

I didn't investigate, but it doesn't work without copying. See logs below

    > /root/taf/taf/testlib/packet_processor.py(415)search_pypacker_layer_in_packet()

    -> for tlv in getattr(packet[pypacker_layer], "tlvlist", [])[:]:
    (Pdb) for tlv in getattr(packet[pypacker_layer], "tlvlist", []): tlv
    (Pdb) for tlv in getattr(packet[pypacker_layer], "tlvlist", [])[:]: tlv
    LLDPChassisId(type_len=207, subtype=4, value=b'\x00\x00 \x00\x10\x02', bytes=b'')
    LLDPPortId(type_len=404, subtype=1, value=b'ge0', bytes=b'')
    LLDPTTL(type_len=602, seconds=28, bytes=b'')
    LLDPPortDescription(type_len=800, value=b'', bytes=b'')
    LLDPSystemName(type_len=A0A, value=b'<sys-name>', bytes=b'')
    LLDPSystemDescription(type_len=C0A, value=b'<sys-desc>', bytes=b'')
    LLDPSystemCapabilities(type_len=E04, capabilities=4, enabled=4, bytes=b'')
    LLDPManagementAddress(type_len=100C, addrlen=5, addrsubtype=1, addrval=b'\x14\x00\n\x02', ifsubtype=2, ifnumber=3E9, oidlen=0,   oid=b'', bytes=b'')
    LLDPDUEnd(tlv_type=0, tlv_len=0, bytes=b'')

</blockquote></details>

Crazy.

---

*[unittests/traffic_generator/test_tg.py, line 75 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYZeC18xM-LGWdpnf1:-Khd5m4I3kjLuwnay7Te:b-2yac4c) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L75)):*
<details><summary><i>Previously, NazarTkachuk (Nazar Tkachuk) wrote…</i></summary><blockquote>

I don't get
</blockquote></details>

```
for init_param in initial_packet_params:
    if not isinstance(...):
        assert ...
        continue
    for received_param in received_packet_params:
        ...
```

The remainder of the function could be further de-indented, but only minimally and it would be somewhat forced.

See also:
* http://thedailywtf.com/articles/Coding-Like-the-Tour-de-France
* http://wiki.c2.com/?ArrowAntiPattern

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/38)*

**Comment by NazarTkachuk** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[taf/testlib/packet_processor.py, line 275 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYVxDAGnEHROQTOvqG:-Ki5CqrLQ3TOxI2c3LTi:b-w0314n) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L275)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Strange, every way that I test it, it works as I expect.

```
>>> class MyO(object):
...   pass
...
>>> myo1 = MyO()
>>> myo1.x = MyO()
>>> myo1.x.y = y = []
>>> myo1.x.y is y
True
>>> y.append(MyO())
>>> y
[<__main__.MyO object at 0x0000000002D871D0>]
>>> myo1.x.y
[<__main__.MyO object at 0x0000000002D871D0>]
```

I don't see an assignment to `packet.lldp` since creating `packet`, what type is `packet.lldp`?  Is this the same type that `packet.lacp` is?

Would `packet.lldp` have a `__setattr__` that does a copy of data before assigning it?
</blockquote></details>

`packet.lldp` is the same  type as `packet.lacp`, all these objects are inherited from pypacker.Packet https://github.com/mike01/pypacker/blob/master/pypacker/pypacker.py

`packet.lldp.tlvlist` and `packet.lacp.tlvlist` are Triggerlist type
 https://github.com/mike01/pypacker/blob/master/pypacker/triggerlist.py

---

*[taf/testlib/packet_processor.py, line 414 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYY-JXiLwVmcSyw3xx:-Ki5A3HQ2Yd3hMzaVlta:b-iovule) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L414)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Crazy.
</blockquote></details>

I was confused as well.

---

*[unittests/traffic_generator/test_tg.py, line 75 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYZeC18xM-LGWdpnf1:-Ki59lsnsTJ5EVeHC-Y0:bfxbebf) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/unittests/traffic_generator/test_tg.py#L75)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

```
for init_param in initial_packet_params:
    if not isinstance(...):
        assert ...
        continue
    for received_param in received_packet_params:
        ...
```

The remainder of the function could be further de-indented, but only minimally and it would be somewhat forced.

See also:
* http://thedailywtf.com/articles/Coding-Like-the-Tour-de-France
* http://wiki.c2.com/?ArrowAntiPattern
</blockquote></details>

Thanks. Updated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/38)*

**Comment by esmacgil** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[taf/testlib/packet_processor.py, line 414 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYY-JXiLwVmcSyw3xx:-Ki7WkDjp2L1YzWHhQw2:b-me3icv) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L414)):*
<details><summary><i>Previously, NazarTkachuk (Nazar Tkachuk) wrote…</i></summary><blockquote>

I was confused as well.
</blockquote></details>

I should've said this before, but apparently it was that crazy: We should put a comment about how the copy is required, so that we know that it fails without the copy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/38)*

**Comment by NazarTkachuk** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[taf/testlib/packet_processor.py, line 414 at r1](https://reviewable.io:443/reviews/taf3/taf/38#-KhYY-JXiLwVmcSyw3xx:-Ki9MJhhmP00FiRxcrMJ:b-896fix) ([raw file](https://github.com/taf3/taf/blob/3125a418ad20133b59b1848845b275ddd2f4bbe7/taf/testlib/packet_processor.py#L414)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

I should've said this before, but apparently it was that crazy: We should put a comment about how the copy is required, so that we know that it fails without the copy.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/38)*

**Comment by esmacgil** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/38#-:-KiBDlCCLwM1OmjtpWBj:bnfp4nl)*

**Pull request merged**
