### PR TITLE
Minor fixes for retrieving powerboard information.

### PR DESCRIPTION
**Pull request by orestkreminskyi**
If powerboard is not present in setup TAF will not fail with KeyError.

Signed-off-by: Orest Kreminskyi <orest.kr@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/taf3/taf/47)

### CODE REVIEW

**Comment by orestkreminskyi** [comment]
@rbbratta @lijenni @esmacgil @seungweonpark 
Could you please review these minor changes?

**Comment by rbbratta** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[taf/testlib/switch_general.py, line 216 at r1](https://reviewable.io:443/reviews/taf3/taf/47#-L7aMZ2388uiYamW2frT:-L7aMZ2388uiYamW2frU:b-aq4lme) ([raw file](https://github.com/taf3/taf/blob/7c2d61cef067e958526d158f13d7a47159fefda1/taf/testlib/switch_general.py#L216)):*
> ```Python
>                 exc_type, exc_value, exc_traceback = sys.exc_info()
>                 traceback_message = traceback.format_exception(exc_type, exc_value, exc_traceback)
>                 self.class_logger.error("Caught an exception while probing the device: %s", "".join(traceback_message))
> ```

you can just use self.class_logger.exception("error while probing device") and it will print the traceback for you,

or self.class_logger.error("", exc_info=True) is the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/47)*

**Comment by orestkreminskyi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[taf/testlib/switch_general.py, line 216 at r1](https://reviewable.io:443/reviews/taf3/taf/47#-L7aMZ2388uiYamW2frT:-L7d8u91e_YvILDs-uw7:b4cdrg4) ([raw file](https://github.com/taf3/taf/blob/7c2d61cef067e958526d158f13d7a47159fefda1/taf/testlib/switch_general.py#L216)):*
<details><summary><i>Previously, rbbratta (Ross Brattain) wrote…</i></summary><blockquote>

you can just use self.class_logger.exception("error while probing device") and it will print the traceback for you,

or self.class_logger.error("", exc_info=True) is the same.


</blockquote></details>

Agree. I've replaced with your suggestion and tested. Works good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/47)*

**Comment by rbbratta** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/47#-:-L7edmfgWuaLWRBkYavs:bnfp4nl)*

**Comment by rbbratta** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/taf3/taf/47#-:-L7ee5vwDfcqSa10UaUz:bnfp4nl)*

**Pull request merged**
