### PR TITLE
Fixed byte-string issues for telnet libs due to migration from python…

### PR DESCRIPTION
**Pull request by orestkreminskyi**
…2 to python3

Signed-off-by: Orest Kreminskyi <orest.kr@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/taf3/taf/48)

### CODE REVIEW

**Comment by orestkreminskyi** [comment]
@rbbratta @esmacgil @seungweonpark @lijenni 
Could you please review these changes for byte-sting issues in telnet libs modules?

**Comment by rbbratta** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[taf/testlib/cli_template.py, line 323 at r1](https://reviewable.io:443/reviews/taf3/taf/48#-L7jyf6-0ivuBnv5lSe0:-L7jyf6-0ivuBnv5lSe1:b8f24ka) ([raw file](https://github.com/taf3/taf/blob/17e86b734d1b65222b554d499d4b06d83beb2f06/taf/testlib/cli_template.py#L323)):*
> ```Python
>         if self.prompt:
>             for single_prompt in self.prompt if isinstance(self.prompt, list) else [self.prompt]:
>                 str_prompt = single_prompt.decode()
> ```

don't use bare decode, always specify the encoding. 

see OpenStack Python3 guidelines

https://wiki.openstack.org/wiki/Python3#bytes.decode_and_unicode.encode


bytes.decode and unicode.encode
Python has a notion of "default encoding": sys.getdefaultencoding(). On Python 2, the default encoding is ASCII, whereas it is UTF-8 on Python 3.

Don't write data.decode() or text.encode() without parameter, because you will use a different encoding on Python 2 and Python 3.

Use an explicit encoding instead. Example: data.decode('utf-8') or text.encode('utf-8'). The right encoding depends on the use case, but UTF-8 is usually a good candidate (it is a superset of ASCII).

---

*[taf/testlib/clitelnet.py, line 75 at r1](https://reviewable.io:443/reviews/taf3/taf/48#-L7jypj_JviEjfIBK62y:-L7jypj_JviEjfIBK62z:bg58php) ([raw file](https://github.com/taf3/taf/blob/17e86b734d1b65222b554d499d4b06d83beb2f06/taf/testlib/clitelnet.py#L75)):*
> ```Python
>         self.prompt = prompt.encode()
>         self.pass_prompt = pass_prompt.encode()
>         self.login_prompt = login_prompt.encode()
> ```

same, use explicit encoding,  utf-8

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/48)*

**Comment by orestkreminskyi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[taf/testlib/cli_template.py, line 323 at r1](https://reviewable.io:443/reviews/taf3/taf/48#-L7jyf6-0ivuBnv5lSe0:-L7y2Wt8Z0QZ3O0sFu1w:b-baeme5) ([raw file](https://github.com/taf3/taf/blob/17e86b734d1b65222b554d499d4b06d83beb2f06/taf/testlib/cli_template.py#L323)):*
<details><summary><i>Previously, rbbratta (Ross Brattain) wrote…</i></summary><blockquote>

don't use bare decode, always specify the encoding. 

see OpenStack Python3 guidelines

https://wiki.openstack.org/wiki/Python3#bytes.decode_and_unicode.encode


bytes.decode and unicode.encode
Python has a notion of "default encoding": sys.getdefaultencoding(). On Python 2, the default encoding is ASCII, whereas it is UTF-8 on Python 3.

Don't write data.decode() or text.encode() without parameter, because you will use a different encoding on Python 2 and Python 3.

Use an explicit encoding instead. Example: data.decode('utf-8') or text.encode('utf-8'). The right encoding depends on the use case, but UTF-8 is usually a good candidate (it is a superset of ASCII).

</blockquote></details>

Thanks for your comment. New patch set has been uploaded.

---

*[taf/testlib/clitelnet.py, line 75 at r1](https://reviewable.io:443/reviews/taf3/taf/48#-L7jypj_JviEjfIBK62y:-L7y2oplVo2BGd7QprHJ:b-896fix) ([raw file](https://github.com/taf3/taf/blob/17e86b734d1b65222b554d499d4b06d83beb2f06/taf/testlib/clitelnet.py#L75)):*
<details><summary><i>Previously, rbbratta (Ross Brattain) wrote…</i></summary><blockquote>

same, use explicit encoding,  utf-8
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/48)*

**Comment by rbbratta** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/48#-:-L8-Qo9wDc1e2U5XsggM:bnfp4nl)*

**Comment by rbbratta** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/48)*

**Pull request merged**
