### PR TITLE
Fixed the add_interface method in openvswitch module, added 2 new methods

### PR DESCRIPTION
**Pull request by orestkreminskyi**
- add_interface()

Added the following new methods in openvswitch module:
 - set_table_record()
 - get_table_record()

Signed-off-by: Orest Kreminskyi <orestx.kreminskyi@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/taf3/taf/29)

### CODE REVIEW

**Comment by orestkreminskyi** [comment]
@rbbratta, @esmacgil, @lijenni please review.

**Comment by esmacgil** [comment]
One request.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[taf/testlib/linux/openvswitch.py, line 156 at r1](https://reviewable.io:443/reviews/taf3/taf/29#-Kef7WoTfa-7pHBoi0Ar:-Kef7WoTfa-7pHBoi0As:b3lymje) ([raw file](https://github.com/taf3/taf/blob/21e8d18ad401b58d9cdd8973de76a45294528211/taf/testlib/linux/openvswitch.py#L156)):*
> ```Python
>                                 kwargs.items()))
>         cmd = 'ovs-vsctl set {table} {rec} {cmd_args}'.format(table=table, rec=rec, cmd_args=cmd_args)
>         self.cli_send_command(cmd)
> ```

That's quite a `lambda`, and while `map` is a powerful tool, I think it is overkill here.  I would rather see:

```
cmd = ['ovs-vsctl', 'set', table, rec]
if kwargs:
    cmd.append(' '.join('{}={}'.format(x, y) if not isinstance(y, tuple) else '{}:{}={}'.format(x, *y) for x, y in kwargs.items())
cmd = ' '.join(cmd)
self.cli_send_command(cmd)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/29#-:-KefAl-Zmd7XFvSzM2ey:b-tw2mhu)*

**Comment by orestkreminskyi** [comment]
Done

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[taf/testlib/linux/openvswitch.py, line 156 at r1](https://reviewable.io:443/reviews/taf3/taf/29#-Kef7WoTfa-7pHBoi0Ar:-KemH1dnF6wDAmb7YlUw:bis0m37) ([raw file](https://github.com/taf3/taf/blob/21e8d18ad401b58d9cdd8973de76a45294528211/taf/testlib/linux/openvswitch.py#L156)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

That's quite a `lambda`, and while `map` is a powerful tool, I think it is overkill here.  I would rather see:

```
cmd = ['ovs-vsctl', 'set', table, rec]
if kwargs:
    cmd.append(' '.join('{}={}'.format(x, y) if not isinstance(y, tuple) else '{}:{}={}'.format(x, *y) for x, y in kwargs.items())
cmd = ' '.join(cmd)
self.cli_send_command(cmd)
```
</blockquote></details>

Agree. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/29#-:-KemHGDBfVvB8wwF3513:bb6un1j)*

**Comment by esmacgil** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[taf/testlib/linux/openvswitch.py, line 156 at r1](https://reviewable.io:443/reviews/taf3/taf/29#-Kef7WoTfa-7pHBoi0Ar:-KeoGiLL58k59NuHnCIC:bg7igkv) ([raw file](https://github.com/taf3/taf/blob/21e8d18ad401b58d9cdd8973de76a45294528211/taf/testlib/linux/openvswitch.py#L156)):*
<details><summary><i>Previously, orestkreminskyi wrote…</i></summary><blockquote>

Agree. Done.
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/29#-:-KeoGr3XiOTKvfET8F1d:bg7igkv)*

**Pull request merged**
