### PR TITLE
Added new file for libvirt service

### PR DESCRIPTION
**Pull request by SavchukRomanLv**
Signed-off-by: Roman Savchuk <romanx.savchuk@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/taf3/taf/23)

### CODE REVIEW

**Comment by SavchukRomanLv** [comment]
Hi, @rbbratta , @esmacgil , @lijenni 
please, review code

**Comment by esmacgil** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[taf/testlib/linux_host_bash.py, line 88 at r1](https://reviewable.io:443/reviews/taf3/taf/23#-Kcxd3wK8nuiDNKTmqlz:-Kcxd3wMtnEDnzLiFKu6:b-y5ix87) ([raw file](https://github.com/taf3/taf/blob/911afda5a8233c80e4bf1fa0ec58985b828cc5ab/taf/testlib/linux_host_bash.py#L88)):*
> ```Python
>         @type  host:  SwitchGeneral
>         """
>         self.host = host
> ```

do we not call `super` by design/intention?

---

*[taf/testlib/linux/libvirt.py, line 38 at r1](https://reviewable.io:443/reviews/taf3/taf/23#-KcxdI4naGTjxVMbD7Bl:-KcxdI4naGTjxVMbD7Bm:bli32mc) ([raw file](https://github.com/taf3/taf/blob/911afda5a8233c80e4bf1fa0ec58985b828cc5ab/taf/testlib/linux/libvirt.py#L38)):*
> ```Python
>         @brief  Initialize libvirt class.
>         """
>         super(Libvirt, self).__init__()
> ```

this is Python2 syntax, `super()` unless we intend for this to be used by earlier versions.

---

*[taf/testlib/linux/libvirt.py, line 42 at r1](https://reviewable.io:443/reviews/taf3/taf/23#-KcxdZhUyUtOWXYSUOOh:-KcxdZhUyUtOWXYSUOOi:bs400fi) ([raw file](https://github.com/taf3/taf/blob/911afda5a8233c80e4bf1fa0ec58985b828cc5ab/taf/testlib/linux/libvirt.py#L42)):*
> ```Python
>         self.service_manager = service_lib.SpecificServiceManager(self.SERVICE, self.cli_send_command)
> 
>     def start(self):
> ```

why not do this and the other three methods with `__getattr__` delegation?

```
def __getattr__(self, item):
    return getattr(self.service_manager, item)
```

as we need different handling, we can add specific methods.

---

*[taf/testlib/linux/libvirt.py, line 67 at r1](https://reviewable.io:443/reviews/taf3/taf/23#-Kcxe6aQ0H1uPFV0NdBb:-Kcxe6aQ0H1uPFV0NdBc:b-ngmqfk) ([raw file](https://github.com/taf3/taf/blob/911afda5a8233c80e4bf1fa0ec58985b828cc5ab/taf/testlib/linux/libvirt.py#L67)):*
> ```Python
>         return self.service_manager.status()
> 
>     def virsh_execute_command(self, command, exp_rc=frozenset({0})):
> ```

why abbreviate expected?

i'm also wondering why we don't do these sorts of methods as a `__call__` method.  if we did `LinuxHostBash` with `cli_send_command` as a `__call__`, then instead of passing `self.cli_send_command` we could pass `self`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by SavchukRomanLv** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[taf/testlib/linux_host_bash.py, line 88 at r1](https://reviewable.io:443/reviews/taf3/taf/23#-Kcxd3wK8nuiDNKTmqlz:-Kd1SVXlf3xYqq27k433:b7t6nh3) ([raw file](https://github.com/taf3/taf/blob/911afda5a8233c80e4bf1fa0ec58985b828cc5ab/taf/testlib/linux_host_bash.py#L88)):*
> why abbreviate expected?
If expected result Fail, tester will be able to set expected_code, and wait for fail. 

---

*[taf/testlib/linux/libvirt.py, line 38 at r1](https://reviewable.io:443/reviews/taf3/taf/23#-KcxdI4naGTjxVMbD7Bl:-Kd1_CoSxiL1IdxzvW69:b-896fix) ([raw file](https://github.com/taf3/taf/blob/911afda5a8233c80e4bf1fa0ec58985b828cc5ab/taf/testlib/linux/libvirt.py#L38)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

this is Python2 syntax, `super()` unless we intend for this to be used by earlier versions.
</blockquote></details>

Done.

---

*[taf/testlib/linux/libvirt.py, line 42 at r1](https://reviewable.io:443/reviews/taf3/taf/23#-KcxdZhUyUtOWXYSUOOh:-Kd1_F9xsalueewKm3RN:b-896fix) ([raw file](https://github.com/taf3/taf/blob/911afda5a8233c80e4bf1fa0ec58985b828cc5ab/taf/testlib/linux/libvirt.py#L42)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

why not do this and the other three methods with `__getattr__` delegation?

```
def __getattr__(self, item):
    return getattr(self.service_manager, item)
```

as we need different handling, we can add specific methods.
</blockquote></details>

Done.

---

*[taf/testlib/linux/libvirt.py, line 67 at r1](https://reviewable.io:443/reviews/taf3/taf/23#-Kcxe6aQ0H1uPFV0NdBb:-Kd1_FyBuqzrRYwztk-p:b-896fix) ([raw file](https://github.com/taf3/taf/blob/911afda5a8233c80e4bf1fa0ec58985b828cc5ab/taf/testlib/linux/libvirt.py#L67)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

why abbreviate expected?

i'm also wondering why we don't do these sorts of methods as a `__call__` method.  if we did `LinuxHostBash` with `cli_send_command` as a `__call__`, then instead of passing `self.cli_send_command` we could pass `self`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by esmacgil** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[taf/testlib/linux_host_bash.py, line 88 at r1](https://reviewable.io:443/reviews/taf3/taf/23#-Kcxd3wK8nuiDNKTmqlz:-Kd2-nd3AGxrqCjLSPzu:buv628) ([raw file](https://github.com/taf3/taf/blob/911afda5a8233c80e4bf1fa0ec58985b828cc5ab/taf/testlib/linux_host_bash.py#L88)):*
<details><summary><i>Previously, SavchukRomanLv wrote…</i></summary><blockquote>

> why abbreviate expected?
If expected result Fail, tester will be able to set expected_code, and wait for fail. 
</blockquote></details>

I understand why the argument is part of the function specification, I don't understand why we are abbreviating _expected_ to _exp_.  We should keep it unabbreviated.

---

*[taf/testlib/linux/libvirt.py, line 39 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd2-DDKtqI1E7huDR7X:-Kd2-DDKtqI1E7huDR7Y:b-7vi3e1) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L39)):*
> ```Python
>         """
>         super().__init__()
>         self.cli_send_command = cli_send_command
> ```

I think we could do

```
self.__call__ = cli_send_command
```

and skip the definition of it below.  What are we adding to/changing with `__call__` below that this wouldn't allow?

---

*[taf/testlib/linux/libvirt.py, line 50 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd1zDNbdCVtqLeDn_s7:-Kd1zDNcTS7zR9dvLGaH:bht4nri) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L50)):*
> ```Python
>         attr = getattr(self.service_manager, name)
>         setattr(self, name, attr)
>         return attr
> ```

Why do we want to _lock in_ the attributes?  If we were doing something slightly more than pure delegation, then I could see avoiding whatever that was, but in the case of pure delegation I see more negatives to lock-in than positives.

---

*[taf/testlib/linux/libvirt.py, line 61 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd1ydd-PO9GMwTMhx95:-Kd1ydd-PO9GMwTMhx96:bgfrago) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L61)):*
> ```Python
>         @rtype:  named tuple
>         """
>         return self.cli_send_command('{}'.format(cmd), expected_rcs=exp_rc)
> ```

Do we need to `format` `cmd`?  If we're worried that `cmd` is not a `string`, then we should feed `cmd`to the `str` constructor.  Further, if we're worried at this point in the code, then why isn't `LinuxHostBash` and similar worried?

Of course, given my other comment about assigning `cli_send_command` to `self.__call__` in `__init__` this would all be moot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by SavchukRomanLv** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[taf/testlib/linux_host_bash.py, line 88 at r1](https://reviewable.io:443/reviews/taf3/taf/23#-Kcxd3wK8nuiDNKTmqlz:-Kd6EfainKEHQagiSatH:b-q6erwn) ([raw file](https://github.com/taf3/taf/blob/911afda5a8233c80e4bf1fa0ec58985b828cc5ab/taf/testlib/linux_host_bash.py#L88)):*
>  expected 
Fixed

---

*[taf/testlib/linux/libvirt.py, line 39 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd2-DDKtqI1E7huDR7X:-Kd6D0Pra8Qwu3Fr0i5K:b31dws3) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L39)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

I think we could do

```
self.__call__ = cli_send_command
```

and skip the definition of it below.  What are we adding to/changing with `__call__` below that this wouldn't allow?
</blockquote></details>

Good idea. But this solution is not working when __call__ is defined in __init__. 

---

*[taf/testlib/linux/libvirt.py, line 50 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd1zDNbdCVtqLeDn_s7:-Kd6BJYR7u7fyDTuyTCV:b-m8pgh1) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L50)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Why do we want to _lock in_ the attributes?  If we were doing something slightly more than pure delegation, then I could see avoiding whatever that was, but in the case of pure delegation I see more negatives to lock-in than positives.
</blockquote></details>

I used setattr in order to have better performance when the same attribute is called multiple times in tests. For example:

1. dir(lhost[1].ui.libvirt.start() )
['SERVICE', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'cli_send_command', 'service_manager', 'virsh']

2. lhost[1].ui.libvirt.start()
"I am in __getattr___ method"

dir(lhost[1].ui.libvirt.start() )
['SERVICE', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'cli_send_command', 'service_manager', 'start', 'virsh']

3. lhost[1].ui.libvirt.start()
"I am not in ___getattr__ method since this attribute was successfully found"

If setattr is not used then __getattr__ will be called after every service method call

---

*[taf/testlib/linux/libvirt.py, line 61 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd1ydd-PO9GMwTMhx95:-Kd6AzozByaA5yr_AK74:bslk04c) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L61)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Do we need to `format` `cmd`?  If we're worried that `cmd` is not a `string`, then we should feed `cmd`to the `str` constructor.  Further, if we're worried at this point in the code, then why isn't `LinuxHostBash` and similar worried?

Of course, given my other comment about assigning `cli_send_command` to `self.__call__` in `__init__` this would all be moot.
</blockquote></details>

Agree with you in relation to format(cmd). Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by SavchukRomanLv** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[taf/testlib/linux/libvirt.py, line 50 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd1zDNbdCVtqLeDn_s7:-Kd6GBWTmlM-GCorjWFT:b2vumck) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L50)):*
<details><summary><i>Previously, SavchukRomanLv wrote…</i></summary><blockquote>

I used setattr in order to have better performance when the same attribute is called multiple times in tests. For example:

1. dir(lhost[1].ui.libvirt.start() )
['SERVICE', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'cli_send_command', 'service_manager', 'virsh']

2. lhost[1].ui.libvirt.start()
"I am in __getattr___ method"

dir(lhost[1].ui.libvirt.start() )
['SERVICE', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'cli_send_command', 'service_manager', 'start', 'virsh']

3. lhost[1].ui.libvirt.start()
"I am not in ___getattr__ method since this attribute was successfully found"

If setattr is not used then __getattr__ will be called after every service method call
</blockquote></details>

Typo in dir(lhost[1].ui.libvirt.start() )  - should be dir(lhost[1].ui.libvirt)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by rbbratta** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[taf/testlib/linux/libvirt.py, line 39 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd2-DDKtqI1E7huDR7X:-Kd7BNosi-GJ7RhxfSc7:bayw4tq) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L39)):*
<details><summary><i>Previously, SavchukRomanLv wrote…</i></summary><blockquote>

Good idea. But this solution is not working when __call__ is defined in __init__. 
</blockquote></details>

these things used to be bound methods in Python 2, so you might have to re-bind.

Or you can try adding it to __call__ on the class object, that should force a re-bind.

self.__class__.__call__ = cli_send_command

or maybe  http://stackoverflow.com/questions/972/adding-a-method-to-an-existing-object-instance

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by rbbratta** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[taf/testlib/linux/libvirt.py, line 39 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd2-DDKtqI1E7huDR7X:-Kd7CaYCqc6Pe74uvn-2:b-9y7acg) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L39)):*
<details><summary><i>Previously, rbbratta (Ross Brattain) wrote…</i></summary><blockquote>

these things used to be bound methods in Python 2, so you might have to re-bind.

Or you can try adding it to __call__ on the class object, that should force a re-bind.

self.__class__.__call__ = cli_send_command

or maybe  http://stackoverflow.com/questions/972/adding-a-method-to-an-existing-object-instance
</blockquote></details>

correct formatting

`self.__class__.__call__ = cli_send_command`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by rbbratta** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[taf/testlib/linux/libvirt.py, line 50 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd1zDNbdCVtqLeDn_s7:-Kd7rFYO0bRDxla5m4zJ:b-t1ld60) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L50)):*
<details><summary><i>Previously, SavchukRomanLv wrote…</i></summary><blockquote>

Typo in dir(lhost[1].ui.libvirt.start() )  - should be dir(lhost[1].ui.libvirt)
</blockquote></details>

 use backticks for inline code, so `__class__` works

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by esmacgil** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[taf/testlib/linux/libvirt.py, line 39 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd2-DDKtqI1E7huDR7X:-Kd8FKrbb19nCosb5W0k:bo3mi1t) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L39)):*
<details><summary><i>Previously, rbbratta (Ross Brattain) wrote…</i></summary><blockquote>

correct formatting

`self.__class__.__call__ = cli_send_command`
</blockquote></details>

It worked for me when I defined a dummy `__call__` that does nothing and then gets replaced by the assignment during `__init__`.

```
def __init__(self, exec_func):
    super().__init__()
    self.__call__ = exec_func

def __call__(self, *args, **kwargs):
    pass
```

Given that as a requirement and how it _looks_, it seems better to do it as you have it now.

The problem with where Ross' is headed is that each new instance would affect all existing instances, when each instance should be able to have its own `cli_send_command`.

---

*[taf/testlib/linux/libvirt.py, line 50 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd1zDNbdCVtqLeDn_s7:-Kd8Gmjhy-ugZKoX5uMU:b-qarfx6) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L50)):*
<details><summary><i>Previously, rbbratta (Ross Brattain) wrote…</i></summary><blockquote>

 use backticks for inline code, so `__class__` works
</blockquote></details>

Yes, that was the positive that I came up with, of course, there's the negative of having to call setattr the first time, and if they aren't called many times this is wasted effort, a negative.  As for the major negative, if `self.service_manager` were to get changed, all the _locked in_ methods would be unaffected.

It isn't a huge deal overall, but my tendency is to do less work, especially the less certain that work or valid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23#-:-Kd8IfFqUV71LgtH5qs8:bnfp4nl)*

**Comment by SavchukRomanLv** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[taf/testlib/linux/libvirt.py, line 39 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd2-DDKtqI1E7huDR7X:-KdAcG-1733-pSzN4qgy:b-iruxvc) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L39)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

It worked for me when I defined a dummy `__call__` that does nothing and then gets replaced by the assignment during `__init__`.

```
def __init__(self, exec_func):
    super().__init__()
    self.__call__ = exec_func

def __call__(self, *args, **kwargs):
    pass
```

Given that as a requirement and how it _looks_, it seems better to do it as you have it now.

The problem with where Ross' is headed is that each new instance would affect all existing instances, when each instance should be able to have its own `cli_send_command`.
</blockquote></details>

Agree with you. You are right. I tested it and each new instance override previous one. 

linux_host_bash.py:
```
self.libvirt = libvirt.Libvirt(self.cli_send_command)
self.libvirt2= libvirt.Libvirt(self.cli_set)
```

```
self.lhost_ui.libvirt.virsh_execute_command('list')
2017-02-17 10:21:54,575 : MainThread : DEBUG : [clissh.CLISSH.exec_command] - root@10.237.222.132: v
DEBUG (exec_command): root@10.237.222.132: v
2017-02-17 10:21:54,581 : MainThread : DEBUG : [clissh.CLISSH.exec_command] - Command output: StdOut: <empty> StdErr:
bash: v: command not found

DEBUG (exec_command): Command output: StdOut: <empty> StdErr:
bash: v: command not found

2017-02-17 10:21:54,662 : MainThread : ERROR : [custom_exceptions.UICmdException.__init__] - Return code is 127, expected frozenset({0}) on command 'v'.
ERROR (__init__): Return code is 127, expected frozenset({0}) on command 'v'.
*** testlib.custom_exceptions.UICmdException: "Return code is 127, expected frozenset({0}) on command 'v'."

(Pdb) self.lhost_ui.libvirt.__class__.__call__
<bound method LinuxHostBash.cli_set of <testlib.linux_host_bash.LinuxHostBash object at 0x7ffff30a3470>>
(Pdb) self.lhost_ui.libvirt2.__class__.__call__
<bound method LinuxHostBash.cli_set of <testlib.linux_host_bash.LinuxHostBash object at 0x7ffff30a3470>>

```

It will be better to do it as we have it now to leave possibility for instance to have its own cli_send_command.

---

*[taf/testlib/linux/libvirt.py, line 50 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd1zDNbdCVtqLeDn_s7:-KdAdTjX509t2yiTLe5_:bvi9x3j) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L50)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Yes, that was the positive that I came up with, of course, there's the negative of having to call setattr the first time, and if they aren't called many times this is wasted effort, a negative.  As for the major negative, if `self.service_manager` were to get changed, all the _locked in_ methods would be unaffected.

It isn't a huge deal overall, but my tendency is to do less work, especially the less certain that work or valid.
</blockquote></details>

Agree, removed setattr from method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by esmacgil** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[taf/testlib/linux/libvirt.py, line 50 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd1zDNbdCVtqLeDn_s7:-KdC8_oeasWZPODpUgUa:bgzex5o) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L50)):*
<details><summary><i>Previously, SavchukRomanLv wrote…</i></summary><blockquote>

Agree, removed setattr from method
</blockquote></details>

I don't see the removal, is there a pull request that needs to be done?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by esmacgil** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by SavchukRomanLv** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[taf/testlib/linux/libvirt.py, line 50 at r2](https://reviewable.io:443/reviews/taf3/taf/23#-Kd1zDNbdCVtqLeDn_s7:-KdPb6_GAV8MON8558Eo:b-vrvbez) ([raw file](https://github.com/taf3/taf/blob/12e834df88aa425b035a544f28eee628ae372fc7/taf/testlib/linux/libvirt.py#L50)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

I don't see the removal, is there a pull request that needs to be done?
</blockquote></details>

New commit was created: 
r4 (843578a) at 2017-02-17 10:52:00Z

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23)*

**Comment by esmacgil** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23#-:-KdW_i7GbK_PRzCFbQKA:bnfp4nl)*

**Comment by orestkreminskyi** [comment]
@rbbratta @esmacgil @lijenni Can this pull request be merged in case if no further comments?

**Comment by esmacgil** [comment]
I say: go for it.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23#-:-Kef2JpiyID3tstHoDMp:bvfmmuh)*

**Comment by rbbratta** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/23#-:-Kep11JF4bBsDqo4NKQ_:bnfp4nl)*

**Pull request merged**
