### PR TITLE
Refactored powerboard.py module:

### PR DESCRIPTION
**Pull request by orestkreminskyi**
- made more generic way to reuse this module for any kind of powerboard with SNMP.
 - removed hard-coded OIDs and added possibility to define OIDs related to powerboard in the config files.

Signed-off-by: Orest Kreminskyi <orest.kr@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/taf3/taf/49)

### CODE REVIEW

**Comment by orestkreminskyi** [comment]
@rbbratta @esmacgil @seungweonpark @lijenni 
Could you please review powerboard changes?

**Comment by rbbratta** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[taf/testlib/powerboard.py, line 39 at r1](https://beta.reviewable.io/reviews/taf3/taf/49#-L9m7hQg-cqJL-tLzCc2:-L9m7hQg-cqJL-tLzCc3:b-n1ipk0) ([raw file](https://github.com/taf3/taf/blob/f7668f988438139abf988df0d084b904cbafe40a/taf/testlib/powerboard.py#L39)):*
> ```Python
>         self.pw_action_oid = config.get("pw_action_oid", "")
>         self.pw_on_cmd = config.get("pw_on_cmd", "1")
>         self.pw_off_cmd = config.get("pw_off_cmd", "0")
> ```

can we convert to str() here?  or why do we convert to str() down in power_status_map

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/taf3/taf/49#-:-L9m86GZ1cPzfdexJ0pB:bnfp4nl)*

**Comment by rbbratta** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[taf/testlib/powerboard.py, line 50 at r1](https://beta.reviewable.io/reviews/taf3/taf/49#-L9mZtZSBpE-lfFHijPh:-L9mZtZSBpE-lfFHijPi:bcy9sp3) ([raw file](https://github.com/taf3/taf/blob/f7668f988438139abf988df0d084b904cbafe40a/taf/testlib/powerboard.py#L50)):*
> ```Python
>     def power_off(self):
>         """Perform power Off of device"""
>         port_action_oid = tuple([int(x) for x in self.pw_action_oid.split('.') + [self.pw_port]])
> ```

should we pre-split the oids?  do we need them as strings?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/taf3/taf/49)*

**Comment by rbbratta** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[taf/testlib/switch_general.py, line 609 at r1](https://beta.reviewable.io/reviews/taf3/taf/49#-L9mgj6F0u_aA0OItGBw:-L9mgj6F0u_aA0OItGBx:b6ni5cj) ([raw file](https://github.com/taf3/taf/blob/3366f7b80c0b10bc0a814d9b83268dbb1d2e1d97/taf/testlib/switch_general.py#L609)):*
> ```Python
>         """
>         self.class_logger.info("Starting Real switch device %s(%s) ..." % (self.name, self.ipaddr))
>         if self.pwboard:
> ```

do we still need to handle the case when pwboard is not defined in config?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/taf3/taf/49)*

**Comment by orestkreminskyi** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[taf/testlib/powerboard.py, line 39 at r1](https://beta.reviewable.io/reviews/taf3/taf/49#-L9m7hQg-cqJL-tLzCc2:-LADBPiB41GuuCgj3lHO:b-l7kxb4) ([raw file](https://github.com/taf3/taf/blob/f7668f988438139abf988df0d084b904cbafe40a/taf/testlib/powerboard.py#L39)):*
> convert to str() down in power_st
yes. we can do it here. Done

---

*[taf/testlib/powerboard.py, line 50 at r1](https://beta.reviewable.io/reviews/taf3/taf/49#-L9mZtZSBpE-lfFHijPh:-LADBXQA7KWwS-6OULKf:beoh0ua) ([raw file](https://github.com/taf3/taf/blob/f7668f988438139abf988df0d084b904cbafe40a/taf/testlib/powerboard.py#L50)):*
<details><summary><i>Previously, rbbratta (Ross Brattain) wrote…</i></summary><blockquote>

should we pre-split the oids?  do we need them as strings?
</blockquote></details>

It is more user intuitive for strings rather than list of integers/strings or tuple of integer/strings. That's why I used strings. 

---

*[taf/testlib/switch_general.py, line 609 at r1](https://beta.reviewable.io/reviews/taf3/taf/49#-L9mgj6F0u_aA0OItGBw:-LADC8qEEb_7UqviYTv_:b-cv6acg) ([raw file](https://github.com/taf3/taf/blob/3366f7b80c0b10bc0a814d9b83268dbb1d2e1d97/taf/testlib/switch_general.py#L609)):*
<details><summary><i>Previously, rbbratta (Ross Brattain) wrote…</i></summary><blockquote>

do we still need to handle the case when pwboard is not defined in config?
</blockquote></details>

Actually no. Pwboard handling was removed in initial pull request. I suppose you've missed these changes in R1 revision.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/taf3/taf/49)*

**Comment by orestkreminskyi** [comment]
Addressed comments.

**Comment by rbbratta** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/taf3/taf/49#-:-LAF-sqDEezJzV7OuxRm:bnfp4nl)*

**Pull request merged**
