### PR TITLE
Extended hugepages module

### PR DESCRIPTION
**Pull request by orestkreminskyi**
- added different HugePage sizes
 - added per node hugepage configuration

Signed-off-by: Orest Kreminskyi <orestx.kreminskyi@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/taf3/taf/26)

### CODE REVIEW

**Comment by orestkreminskyi** [comment]
@rbbratta, @esmacgil, @lijenni please review.

**Comment by esmacgil** [comment]
I'd like to see some greater code sharing/reuse.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[taf/testlib/linux/hugepages.py, line 60 at r1](https://reviewable.io:443/reviews/taf3/taf/26#-KeaDe_kAAyNsTkYeaOg:-KeaDe_kAAyNsTkYeaOh:b-v4msnx) ([raw file](https://github.com/taf3/taf/blob/62a4009488b1c97c0c02d41abfbfdd56a92a5cc0/taf/testlib/linux/hugepages.py#L60)):*
> ```Python
>         if per_node is not None:
>             output = self.cli_send_command(
>                 command='cat /sys/devices/system/node/node{}/hugepages/hugepages-{}kB/nr_hugepages'.format(per_node, hugepage_size)).stdout
> ```

It seems these three new methods are rather common, I think a helper would be useful:

```
def _hugepages_helper(self, kwargs):
    if kwargs.get('per_node') is not None:
        template = '{mode} /sys/devices/system/node/node{per_node}/hugepages/hugepages-{hugepage_size}kb/nr_hugepages'
    else:
        template = '{mode} /sys/kernel/mm/hugepages/hugepages-{hugepage_size}kb/nr_hugepages'

    command = per_node_template.format(**kwargs)
    return self.cli_send_command(command)

def get_number(...):
    output = self._hugepages_helper({'mode': 'cat', 'per_node': per_node, 'nr_hugepages': nr_hugepages}).stdout
    return int(output)
```

---

*[taf/testlib/linux/hugepages.py, line 76 at r1](https://reviewable.io:443/reviews/taf3/taf/26#-KeaEXxkSjISlm9utCPy:-KeaEXxkSjISlm9utCPz:b-nuiv61) ([raw file](https://github.com/taf3/taf/blob/62a4009488b1c97c0c02d41abfbfdd56a92a5cc0/taf/testlib/linux/hugepages.py#L76)):*
> ```Python
>         @return:  Returns number of free hugepages
>         """
>         if per_node is not None:
> ```

With the line 60 suggestion, this becomes:

```
def get_number(...):
    output = self._hugepages_helper({'mode': 'cat', 'per_node': per_node, 'nr_hugepages': nr_hugepages}).stdout
    return int(output)
```

---

*[taf/testlib/linux/hugepages.py, line 94 at r1](https://reviewable.io:443/reviews/taf3/taf/26#-KeaEd6jRW_3RysqrAfW:-KeaEd6jRW_3RysqrAfX:b-y9icpu) ([raw file](https://github.com/taf3/taf/blob/62a4009488b1c97c0c02d41abfbfdd56a92a5cc0/taf/testlib/linux/hugepages.py#L94)):*
> ```Python
>         @type hugepage_size: int
>         """
>         if per_node is not None:
> ```

With the line 60 suggestion, this becomes:

```
def change_number(...):
    self._hugepages_helper({'mode': 'echo {} >'.format(nr_hugepages), 'per_node': per_node, 'hugepage_size': hugepage_size})
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/26#-:-KeaILpdZPZMujmxikPl:b-xz4b2i)*

**Comment by orestkreminskyi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[taf/testlib/linux/hugepages.py, line 60 at r1](https://reviewable.io:443/reviews/taf3/taf/26#-KeaDe_kAAyNsTkYeaOg:-KeczGe9K6b23TD6__m-:b-woidxl) ([raw file](https://github.com/taf3/taf/blob/62a4009488b1c97c0c02d41abfbfdd56a92a5cc0/taf/testlib/linux/hugepages.py#L60)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

It seems these three new methods are rather common, I think a helper would be useful:

```
def _hugepages_helper(self, kwargs):
    if kwargs.get('per_node') is not None:
        template = '{mode} /sys/devices/system/node/node{per_node}/hugepages/hugepages-{hugepage_size}kb/nr_hugepages'
    else:
        template = '{mode} /sys/kernel/mm/hugepages/hugepages-{hugepage_size}kb/nr_hugepages'

    command = per_node_template.format(**kwargs)
    return self.cli_send_command(command)

def get_number(...):
    output = self._hugepages_helper({'mode': 'cat', 'per_node': per_node, 'nr_hugepages': nr_hugepages}).stdout
    return int(output)
```
</blockquote></details>

Done with minor changes.

---

*[taf/testlib/linux/hugepages.py, line 76 at r1](https://reviewable.io:443/reviews/taf3/taf/26#-KeaEXxkSjISlm9utCPy:-KeczFSHDvY1IEJ7Rw38:b-896fix) ([raw file](https://github.com/taf3/taf/blob/62a4009488b1c97c0c02d41abfbfdd56a92a5cc0/taf/testlib/linux/hugepages.py#L76)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

With the line 60 suggestion, this becomes:

```
def get_number(...):
    output = self._hugepages_helper({'mode': 'cat', 'per_node': per_node, 'nr_hugepages': nr_hugepages}).stdout
    return int(output)
```
</blockquote></details>

Done.

---

*[taf/testlib/linux/hugepages.py, line 94 at r1](https://reviewable.io:443/reviews/taf3/taf/26#-KeaEd6jRW_3RysqrAfW:-KeczDClD9IHCH4rlUqO:b-896fix) ([raw file](https://github.com/taf3/taf/blob/62a4009488b1c97c0c02d41abfbfdd56a92a5cc0/taf/testlib/linux/hugepages.py#L94)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

With the line 60 suggestion, this becomes:

```
def change_number(...):
    self._hugepages_helper({'mode': 'echo {} >'.format(nr_hugepages), 'per_node': per_node, 'hugepage_size': hugepage_size})
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/26)*

**Comment by esmacgil** [comment]
Thanks for the hugepages refactor.  Sorry for not looking more closely earlier at the mount/umount code.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[taf/testlib/linux/hugepages.py, line 70 at r2](https://reviewable.io:443/reviews/taf3/taf/26#-Kef5SVhijLIt_bFi7tY:-Kef5SVhijLIt_bFi7tZ:bnyc2hs) ([raw file](https://github.com/taf3/taf/blob/2bbb4a7b254484c6b3c187b4ec3a0d145e4d41b6/taf/testlib/linux/hugepages.py#L70)):*
> ```Python
>         else:
>             cmd = "mount -t hugetlbfs nodev {mnt_dir}".format(mnt_dir=mnt_dir)
>         self.cli_send_command(cmd)
> ```

It seems that I didn't look at this so closely.  I appreciate the usage of `join` and `format`, but the innermost `join` seems better handled by the `format` within it.  And then the outer `format` handled by a `join` following the building of a `list`.  Why not:

```
cmd = ['mount', '-t', 'hugelbfs', 'nodev', mnt_dir]
if kwargs:
    cmd.append(' '.join('--{} {}'.format(x, y) for x, y in kwargs.items())
cmd = ' '.join(cmd)
self.cli_send_command(cmd)
```

Then we don't have to cast `y` to a `str` and we don't have to create the two element `list` values for each `item` in the `dict`.

And of course, a similar treatment can be applied to the `umount`method immediately following.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/26#-:-Kef6oFB6eZuXNsltGSO:b-9wqk2m)*

**Comment by orestkreminskyi** [comment]
No worries. Comments are addressed. 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[taf/testlib/linux/hugepages.py, line 70 at r2](https://reviewable.io:443/reviews/taf3/taf/26#-Kef5SVhijLIt_bFi7tY:-KemKY06iFCZPj50f2Ku:b-w0dzzg) ([raw file](https://github.com/taf3/taf/blob/2bbb4a7b254484c6b3c187b4ec3a0d145e4d41b6/taf/testlib/linux/hugepages.py#L70)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

It seems that I didn't look at this so closely.  I appreciate the usage of `join` and `format`, but the innermost `join` seems better handled by the `format` within it.  And then the outer `format` handled by a `join` following the building of a `list`.  Why not:

```
cmd = ['mount', '-t', 'hugelbfs', 'nodev', mnt_dir]
if kwargs:
    cmd.append(' '.join('--{} {}'.format(x, y) for x, y in kwargs.items())
cmd = ' '.join(cmd)
self.cli_send_command(cmd)
```

Then we don't have to cast `y` to a `str` and we don't have to create the two element `list` values for each `item` in the `dict`.

And of course, a similar treatment can be applied to the `umount`method immediately following.
</blockquote></details>

Good suggestion. Done for both methods (mount, umount)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/26#-:-Ked0BREqd2bhnIrstUw:b-5w4hi4)*

**Comment by esmacgil** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/26#-:-KeoEEQ_OonAECoMKOcM:bnfp4nl)*

**Pull request merged**
