### PR TITLE
Fixed scope of 'with' statement body for logfile in XML.py

### PR DESCRIPTION
**Pull request by NazarTkachuk**
Signed-off-by: Tkachuk <nazarx.tkachuk@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/taf3/taf/34)

### CODE REVIEW

**Comment by NazarTkachuk** [comment]
Please review @rbbratta @seungweonpark @lijenni @esmacgil

**Comment by esmacgil** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[reporting/reports/XML.py, line 651 at r1](https://reviewable.io:443/reviews/taf3/taf/34#-KhO5dbbArPwgV9JlBiw:-KhO5dbbArPwgV9JlBix:b-qzuoog) ([raw file](https://github.com/taf3/taf/blob/bb50af755ad01ba7f00d637299619ad0d4947b73/reporting/reports/XML.py#L651)):*
> ```Python
>             else:
>                 self.class_logger.info("XML report is successfully dumped to file %s.", dump_logfile)
>                 self.tests = []
> ```

Do the lines from here to the end of the function need to be inside the context?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/34)*

**Comment by NazarTkachuk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[reporting/reports/XML.py, line 651 at r1](https://reviewable.io:443/reviews/taf3/taf/34#-KhO5dbbArPwgV9JlBiw:-KhXwzdnb83RcE4Ihl9X:b-bjksku) ([raw file](https://github.com/taf3/taf/blob/bb50af755ad01ba7f00d637299619ad0d4947b73/reporting/reports/XML.py#L651)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

Do the lines from here to the end of the function need to be inside the context?
</blockquote></details>

These lines refer to `else` from statement `try..except..else`. It means that we create HTML report in case if test results were written to XML file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/34)*

**Comment by esmacgil** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[reporting/reports/XML.py, line 651 at r1](https://reviewable.io:443/reviews/taf3/taf/34#-KhO5dbbArPwgV9JlBiw:-KhYPNVNWzoC3u0zazwC:b-2be05y) ([raw file](https://github.com/taf3/taf/blob/bb50af755ad01ba7f00d637299619ad0d4947b73/reporting/reports/XML.py#L651)):*
<details><summary><i>Previously, NazarTkachuk (Nazar Tkachuk) wrote…</i></summary><blockquote>

These lines refer to `else` from statement `try..except..else`. It means that we create HTML report in case if test results were written to XML file.
</blockquote></details>

My apologies for not being more explicit, if the lines don't need to be inside the context, then I'd prefer to see the `except` block have a `return` statement and get rid of the `else` block which would allow for the context to end before the function wraps up, at least in the successful case.

Now that I look further though, why not do more of the work before the context?

```
if self.infodict:
    self.tests.append(...)
try:
    testsuite = self.Junit.testsuite(...)
except Exception as err:
    self.class_logger.error(...)
    return
with open(...):
    logfile.write(....)
    if self._css:
        logfile.write(...)
    if self._xsl:
        logfile.write(...)
    logfile.write(testsuite)
self.class_logger.info(...)
self.tests = []
...
```

My intention is to do as little computation during the file writing context as possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/34)*

**Comment by NazarTkachuk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[reporting/reports/XML.py, line 651 at r1](https://reviewable.io:443/reviews/taf3/taf/34#-KhO5dbbArPwgV9JlBiw:-KhbgwCxAFgVvA3x6Lfz:b-8dtjzq) ([raw file](https://github.com/taf3/taf/blob/bb50af755ad01ba7f00d637299619ad0d4947b73/reporting/reports/XML.py#L651)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

My apologies for not being more explicit, if the lines don't need to be inside the context, then I'd prefer to see the `except` block have a `return` statement and get rid of the `else` block which would allow for the context to end before the function wraps up, at least in the successful case.

Now that I look further though, why not do more of the work before the context?

```
if self.infodict:
    self.tests.append(...)
try:
    testsuite = self.Junit.testsuite(...)
except Exception as err:
    self.class_logger.error(...)
    return
with open(...):
    logfile.write(....)
    if self._css:
        logfile.write(...)
    if self._xsl:
        logfile.write(...)
    logfile.write(testsuite)
self.class_logger.info(...)
self.tests = []
...
```

My intention is to do as little computation during the file writing context as possible.
</blockquote></details>

Good point! Updated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/34)*

**Comment by esmacgil** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[reporting/reports/XML.py, line 651 at r1](https://reviewable.io:443/reviews/taf3/taf/34#-KhO5dbbArPwgV9JlBiw:-KhdC7apgKOCW86YIaCi:b-ytnhbn) ([raw file](https://github.com/taf3/taf/blob/bb50af755ad01ba7f00d637299619ad0d4947b73/reporting/reports/XML.py#L651)):*
<details><summary><i>Previously, NazarTkachuk (Nazar Tkachuk) wrote…</i></summary><blockquote>

Good point! Updated
</blockquote></details>

I realized later that this approach also means the dump log file is only created if the test suite portion is created.  I think this is fine, I hope you realized this implication and agree that it is acceptable/desirable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/34#-:-KhdCc0UhJ2h_yFzn630:bnfp4nl)*

**Comment by NazarTkachuk** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[reporting/reports/XML.py, line 651 at r1](https://reviewable.io:443/reviews/taf3/taf/34#-KhO5dbbArPwgV9JlBiw:-Ki4QfV9i4So2W7AOO7J:byjr17u) ([raw file](https://github.com/taf3/taf/blob/bb50af755ad01ba7f00d637299619ad0d4947b73/reporting/reports/XML.py#L651)):*
<details><summary><i>Previously, esmacgil (Edward MacGillivray) wrote…</i></summary><blockquote>

I realized later that this approach also means the dump log file is only created if the test suite portion is created.  I think this is fine, I hope you realized this implication and agree that it is acceptable/desirable.
</blockquote></details>

Agree with you. I verified that HTML report is generated in positive case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/taf3/taf/34)*

**Pull request merged**
